apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-l4-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path: /var/share/nginx/html
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
