apiVersion: v1
kind: Service
metadata:
  name: usuario
labels:
 app: usuario
spec:
 type: ClusterIP
 selector:
   app: usuario
ports:
  name: http
  protocol: TCP
  port: 80
  targetPort: 8080

    	
