apiVersion: v1
kind: Service
metadata:
  name: cuenta-bancaria
labels:
 app: cuenta-bancaria
spec:
 type: ClusterIP
 selector:
   app: cuenta-bancaria
ports:
  name: http
  protocol: TCP
  port: 80
  targetPort: 8080

    	
