apiVersion: v1
kind: Service
metadata:
  name: catalogo-libros
  labels:
    app: catalogo-libros
spec:
  type: ClusterIP
  selector:
    app: catalogo-libros
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080