apiVersion: v1
kind: Service
metadata:
  name: app-banca-service
  labels:
    app: app-banca
spec:
  type: ClusterIP
  selector:
    app: app-banca
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080