apiVersion: v1
kind: Ingress
metadata:
  name: nginx_webapp-ingress
  labels:
    app: nginx_webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: reto.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx_webapp-service
                port:
                  number: 80
