apiVersion: v1
kind: Service
metadata:
  name: nginx_webapp-service
  labels:
    app: nginx_webapp
spec:
  type: ClusterIP
  selector:
    app: nginx_webapp
  ports:
    - name: http
      port: 80
      targetPort: 80
