apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-data-pco-config
  labels:
    app: spring-data-pco
data:

  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS: "always"
