apiVersion: v1
kind: Secret
metadata:
  name: spring-data-pco-secret
  labels:
    app: spring-data-pco
    version: "v1.0.0"
type: Opaque
data:
  DB_PASSWORD: c2VjdXJvUGFzc3dvcmQ= 
  JWT_SECRET: c2VjcmV0S2V5MTIz 
