apiVersion: v1

kind: Service
metadata:
  name: spring-data-pco
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: spring-data-pco
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
